language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - echo "Entering in app folder"
  - cd app/
  - echo "Building spring boot application"
  - mvn clean package
  - cd ..
  - echo "Turn back to main folder"
script:
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag docker-to-aws-with-java:latest sandromendes/docker-to-aws-with-java:latest;
    docker push sandromendes/docker-to-aws-with-java;
  on:
    branch: main
notifications:
  email: false