version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd app/
            mvn -B -DskipTests clean package
            cd..
      - run:
          name: Test
          command: mvn test
      - run:
          name: "Build and push Docker image"
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS docker login docker.io
            docker tag docker-to-aws-with-java:latest sandromendes/docker-to-aws-with-java:latest;
            docker push sandromendes/docker-to-aws-with-java;

workflows:
  test-and-deploy:
    jobs:
      - build-and-test